### ISSUE TITLE
Ui界面点击存货信息功能闪退

### ISSUE THREAD

**Issue by vae-say** [jhqi/store-management-system#2]
求大佬更新代码，界面提示如下:
进程已结束，退出代码为 -1073740791 (0xC0000409)

**Comment by jhqi** [comment]
这个问题我倒没遇到过
release更新至了2.6版本，源码也同步是最新的了。你可以看看后台报错是啥

**Comment by vae-say** [comment]
大佬，用了你的新的版本，闪退没有了，大佬牛逼yyds，我学习学习代码。

**Comment by jhqi** [comment]
哈哈，这个代码真没啥值得学习的。
没有面向对象思想，代码冗余很多
结构一塌糊涂
sql甚至还是注入
小作坊玩意，当年接的个小活儿，练手写的

**Comment by vae-say** [comment]
至少我写不出来，研究研究代码。:)
